Added getIdTokenResult support
atn832/firebase_auth_mocks pull request #60
Opened 2022-06-16 23:57 UTC by simplecohesion

**What this PR contains**
- Adds ```IdTokenResult? _idTokenResult``` private property in MockUser
- Adds ```IdTokenResult? idTokenResult``` optional property for MockUser constructor
- Overrides ```dart Future<IdTokenResult> getIdTokenResult([bool forceRefresh = false])``` in MockUser to return the the _idTokenResult property as a Future value
- Adds idTokenResult mock data to the test user in firebase_auth_mocks_test.dart

2022-06-30 14:34 UTC, atn832 commented
Thanks for the PR @simplecohesion. Would you mind writing a unit test as well to show how it works, and prevent others from accidentally breaking your code in the future?

2022-09-12 11:12 UTC, AngeloAvv commented
Hey @atn832 , any updates on this?

2022-09-12 23:17 UTC, atn832 requested changes

2022-09-12 23:17 UTC, atn832 commented on lib/src/mock_user.dart
> +  Future<IdTokenResult> getIdTokenResult([bool forceRefresh = false]) {
Can you write a unit test that actually uses this new method?

2022-10-18 23:23 UTC, atn832 commented
Thanks for proposing this PR. I just merged #73 since it came with tests.

2022-10-18 23:23 UTC, closed without merging